apiVersion: apps/v1
kind: Deployment
metadata:
  name: connecthub-report
  namespace: connecthub
  labels:
    app: report
spec:
  replicas: 1  # Number of pods to runs
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
      - name: report
        image: DOCKER_IMAGE  # Replace with your Docker image names
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "100m"
        envFrom:
          - secretRef:
              name: auth-token-secrets
          - secretRef:
              name: mysql-secrets
          - secretRef:
              name: prod-secrets
