name: esl Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'esl/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'esl/**'



env:
  AWS_REGION: ap-south-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: connecthub_telephony           # set this to your Amazon ECR repository name
  ECS_SERVICE: fastapi-esl                 # set this to your Amazon ECS service name
  ECS_CLUSTER: connecthub                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs1-$IMAGE_TAG  -f docker/esl/fs1/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs1-$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs1-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs2-$IMAGE_TAG  -f docker/esl/fs2/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs2-$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs2-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs3-$IMAGE_TAG   -f docker/esl/fs3/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs3-$IMAGE_TAG 
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs3-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs4-$IMAGE_TAG   -f docker/esl/fs4/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs4-$IMAGE_TAG 
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs4-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs5-$IMAGE_TAG   -f docker/esl/fs5/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs5-$IMAGE_TAG 
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs5-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs6-$IMAGE_TAG   -f docker/esl/fs6/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs6-$IMAGE_TAG 
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs6-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs7-$IMAGE_TAG   -f docker/esl/fs7/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs7-$IMAGE_TAG 
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs7-$IMAGE_TAG" >> $GITHUB_OUTPUT

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:fs8-$IMAGE_TAG   -f docker/esl/fs8/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:fs8-$IMAGE_TAG 
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:fs8-$IMAGE_TAG" >> $GITHUB_OUTPUT


    - name: Update kube config
      run: aws eks update-kubeconfig --name $ECS_CLUSTER --region $AWS_REGION

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i.bak "s|IMAGEPRODUCERFS1|$ECR_REGISTRY/$ECR_REPOSITORY:fs1-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS2|$ECR_REGISTRY/$ECR_REPOSITORY:fs2-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS3|$ECR_REGISTRY/$ECR_REPOSITORY:fs3-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS4|$ECR_REGISTRY/$ECR_REPOSITORY:fs4-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS5|$ECR_REGISTRY/$ECR_REPOSITORY:fs5-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS6|$ECR_REGISTRY/$ECR_REPOSITORY:fs6-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS7|$ECR_REGISTRY/$ECR_REPOSITORY:fs7-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        sed -i.bak "s|IMAGEPRODUCERFS8|$ECR_REGISTRY/$ECR_REPOSITORY:fs8-$IMAGE_TAG|g" k8/esl/eslevent.yml && \
        kubectl apply -f k8/esl/eslevent.yml 
