apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-eslevent
  namespace: connecthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-eslevent
  template:
    metadata:
      labels:
        app: fastapi-eslevent
    spec:
      containers:
        - name: fastapi-eslevent-fs1
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs1:latest
          envFrom:
            - secretRef:
                name: esl-details-fs1
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

        - name: fastapi-eslevent-fs2
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs2:latest
          envFrom:
            - secretRef:
                name: esl-details-fs2
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

        - name: fastapi-eslevent-fs3
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs3:latest
          envFrom:
            - secretRef:
                name: esl-details-fs3
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

        - name: fastapi-eslevent-fs4
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs4:latest
          envFrom:
            - secretRef:
                name: esl-details-fs4
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

        - name: fastapi-eslevent-fs5
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs5:latest
          envFrom:
            - secretRef:
                name: esl-details-fs5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

        - name: fastapi-eslevent-fs6
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs6:latest
          envFrom:
            - secretRef:
                name: esl-details-fs6
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

        - name: fastapi-eslevent-fs7
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs7:latest
          envFrom:
            - secretRef:
                name: esl-details-fs7
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
              
        - name: fastapi-eslevent-fs8
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/esl-fs8:latest
          envFrom:
            - secretRef:
                name: esl-details-fs8
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-eslevent
  namespace: connecthub
spec:
  selector:
    app: fastapi-eslevent
  ports:
    - name: producer  # Fixed typo
      port: 3000
      targetPort: 3000
