apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketioagent
  namespace: connecthub
  labels:
    app: socketioagent
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: socketioagent
  template:
    metadata:
      labels:
        app: socketioagent
    spec:
      containers:
      - name: socketioagent
        image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/socketioagent:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
