apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  namespace: connecthub
  labels:
    app: ai
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/ai   # Replace with your Docker image name
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: auth-token-secrets
            - secretRef:
                name: mysql-secrets
