from fastapi import status, HTTPException
from fastapi.responses import JSONResponse
from config import settings
from models.dto import TokenModel
from typing import List
from urllib.parse import quote
import asyncio, uuid, jwt, os, xml.etree.ElementTree as ET
import pytz
from fastapi_mail import FastMail, ConnectionConfig, MessageSchema
from datetime import datetime, date

IST = pytz.timezone("Asia/Kolkata")
conf = ConnectionConfig(
    MAIL_USERNAME="reports@pulseindia.in",
    MAIL_PASSWORD="rjho xycx srue jomm",
    MAIL_FROM="reports@pulseindia.in",
    MAIL_PORT=587,
    MAIL_SERVER="smtp.gmail.com",
    MAIL_STARTTLS=True,
    MAIL_SSL_TLS=False,
    USE_CREDENTIALS=True
)

def decode(token: str):
    try:
        token_data = jwt.decode(token, settings.AUTH_TOKEN_SECRET_KEY, algorithms=[settings.AUTH_TOKEN_ALGORITHM])
        return TokenModel(**token_data)
    except jwt.ExpiredSignatureError:
        return JSONResponse(
            status_code=status.HTTP_401_UNAUTHORIZED,
            content={
                "message": "Token Expired"
            }
        )
    except jwt.InvalidTokenError:
        return JSONResponse(
            status_code=status.HTTP_401_UNAUTHORIZED,
            content={
                "message": "Token Invalid"
            }
        )

async def alert(proxyname: str, sourceip: str, domain: str):

    subject = f"[ALERT] Suspicious SIP Activity from {sourceip}"

    body = f"""
    <html>
    <body style="margin:0; padding:0; background-color:#f4f6f8; font-family:Arial, sans-serif;">
    
    <div style="max-width:650px; margin:30px auto; background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 4px 12px rgba(0,0,0,0.08);">

        <!-- Header -->
        <div style="background:#d93025; color:#ffffff; padding:18px 24px;">
            <h2 style="margin:0; font-size:20px;">🚨 Security Alert</h2>
            <p style="margin:5px 0 0; font-size:13px; opacity:0.9;">
                Suspicious SIP activity detected
            </p>
        </div>

        <!-- Body -->
        <div style="padding:25px;">

            <p style="font-size:14px; color:#333; margin-top:0;">
                We detected unusual SIP traffic that may indicate scanning, brute-force attempts, or abuse.
            </p>

            <!-- Highlight IP -->
            <div style="background:#fff3f3; border-left:4px solid #d93025; padding:12px 15px; margin:20px 0;">
                <strong style="color:#d93025;">Source IP:</strong>
                <span style="font-family:monospace; font-size:14px;">{sourceip}</span>
            </div>

            <!-- Details Table -->
            <table style="width:100%; border-collapse:collapse; font-size:14px;">
                <tr>
                    <td style="padding:10px; border:1px solid #eee;"><strong>Proxy</strong></td>
                    <td style="padding:10px; border:1px solid #eee;">{proxyname}</td>
                </tr>
                <tr>
                    <td style="padding:10px; border:1px solid #eee;"><strong>Detected At</strong></td>
                    <td style="padding:10px; border:1px solid #eee;">
                        {IST.localize(datetime.now()).strftime('%Y-%m-%d %H:%M:%S')}
                    </td>
                </tr>
            </table>

            <!-- Action Box -->
            <div style="margin-top:25px; padding:15px; background:#f1f8ff; border-left:4px solid #1a73e8;">
                <p style="margin:0 0 8px; font-weight:bold;">Recommended Actions</p>
                <ul style="margin:0; padding-left:18px; font-size:13px; color:#444;">
                    <li>Verify if the IP is trusted</li>
                    <li>Check OpenSIPS logs (auth failures / flood)</li>
                    <li>Apply block using iptables</li>
                </ul>
            </div>

        </div>

        <!-- Footer -->
        <div style="padding:15px 25px; background:#fafafa; font-size:12px; color:#777; text-align:center;">
            Generated by <strong>{domain}</strong><br>
            This is an automated security notification.
        </div>

    </div>

    </body>
    </html>
    """

    message = MessageSchema(
        subject=subject,
        recipients=["swd@ispbazaarindia.com"],
        cc=["swd@ispbazaarindia.com"],
        body=body,
        subtype="html"
    )

    fm = FastMail(conf)

    try:
        await fm.send_message(message)
        print("Alert email sent successfully.")
    except Exception as e:
        print(f"Failed to send alert email: {e}")