apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-auth
  namespace: connecthub
  labels:
    app: fastapi-auth
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: fastapi-auth
  template:
    metadata:
      labels:
        app: fastapi-auth
    spec:
      containers:
      - name: fastapi-auth
        image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/auth:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
        - secretRef:
            name: auth-token-secrets
        - secretRef:
            name: mysql-secrets
