apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevenlabs-proxy
  namespace: connecthub
  labels:
    app: elevenlabs-proxy
spec:
  replicas: 1 # Match AI pod replica count
  selector:
    matchLabels:
      app: elevenlabs-proxy
  template:
    metadata:
      labels:
        app: elevenlabs-proxy
    spec:
      containers:
        - name: elevenlabs-proxy
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/elevenlabs-standalone   # Replace with your Docker image name
          ports:
            - containerPort: 8050
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: auth-token-secrets
            - secretRef:
                name: mysql-secrets
