apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: connecthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/node-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: auth-token-secrets
            - secretRef:
                name: mysql-secrets
