apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-longrunningtask
  namespace: connecthub
  labels:
    app: longrunningtask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longrunningtask
  template:
    metadata:
      labels:
        app: longrunningtask
    spec:
      containers:
      - name: longrunningtask
        image: DOCKER_IMAGE  # Replace with your Docker image name
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
          - secretRef:
              name: kafka-details
          - secretRef:
              name: mysql-details
          - secretRef:
              name: mongo-details

