export const datas = [
    {
        name: "Allan Christopher",
        role: "Admin",
        extension: "1000",
        number: "1234567893",
        department: "Software",
        language: "English",
        email: "allanchristopher123@gmail.com",
    },
    {
        name: "Sarah Williams",
        role: "Manager",
        extension: "1001",
        number: "9876543210",
        department: "HR",
        language: "English",
        email: "sarahwilliams@masadail.com",
    },
    {
        name: "Sarah Williams",
        role: "Manager",
        extension: "1001",
        number: "9876543210",
        department: "HR",
        language: "English",
        email: "sarahwilliamsasdsa@mail.com",
    },
    {
        name: "Sarah Williams",
        role: "Manager",
        extension: "1001",
        number: "9876543210",
        department: "HR",
        language: "English",
        email: "sarahwilliamasdass@mail.com",
    },
    {
        name: "Sarah Williams",
        role: "Manager",
        extension: "1001",
        number: "9876543210",
        department: "HR",
        language: "English",
        email: "sarahwilliams@maasdasdsail.com",
    },
    {
        name: "David Smith",
        role: "Developer",
        extension: "1002",
        number: "5551234567",
        department: "Development",
        language: "English",
        email: "david.smith@example.com",
    },
    {
        name: "Emily Johnson",
        role: "Designer",
        extension: "1003",
        number: "5559876543",
        department: "Design",
        language: "English",
        email: "emily.johnson@gmail.com",
    },
    {
        name: "Michael Brown",
        role: "Support",
        extension: "1004",
        number: "5554567890",
        department: "Support",
        language: "English",
        email: "michael.brown@company.com",
    },
    {
        name: "Jessica Davis",
        role: "Admin",
        extension: "1005",
        number: "5557890123",
        department: "Administration",
        language: "English",
        email: "jessica.davis@admin.com",
    },
    {
        name: "Robert Lee",
        role: "Developer",
        extension: "1006",
        number: "5553216548",
        department: "Development",
        language: "English",
        email: "robert.lee@devmail.com",
    },
    {
        name: "Sophia Martin",
        role: "Manager",
        extension: "1007",
        number: "5556549871",
        department: "Marketing",
        language: "English",
        email: "sophia.martin@marketing.com",
    },
    {
        name: "William Harris",
        role: "HR Specialist",
        extension: "1008",
        number: "5554328765",
        department: "HR",
        language: "English",
        email: "william.harris@hr.com",
    },
    {
        name: "Olivia Wilson",
        role: "Sales Executive",
        extension: "1009",
        number: "5558765432",
        department: "Sales",
        language: "English",
        email: "olivia.wilson@sales.com",
    },
];

export const totalcount = "13";


