apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-whatsapp
  namespace: connecthub
  labels:
    app: fastapi-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-whatsapp
  template:
    metadata:
      labels:
        app: fastapi-whatsapp
    spec:
      containers:
      - name: fastapi-whatsapp
        image: DOCKER_IMAGE
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
        - secretRef:
            name: auth-token-secrets
        - secretRef:
            name: mysql-secrets
        - secretRef:
            name: s3-secrets


