apiVersion: v1
kind: Service
metadata:
  name: emergency-ivr-service
  namespace: connecthub
spec:
  selector:
    app: emergency-ivr-consumer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
