apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-telephony
  namespace: connecthub
  labels:
    app: fastapi-telephony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-telephony
  template:
    metadata:
      labels:
        app: fastapi-telephony
    spec:
      containers:
      - name: fastapi-telephony
        image: DOCKER_IMAGE
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: APP_FOLDER_NAME
          value: "queue_app1"   # Change per deployment if needed
        volumeMounts:
        - name: efs-storage
          mountPath: /opt/freeswitch/storage
        envFrom:
        - secretRef:
            name: auth-token-secrets
        - secretRef:
            name: mysql-secrets
        - secretRef:
            name: freeswitch-secrets
        - secretRef:
            name: s3-secrets
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc
