apiVersion: apps/v1
kind: Deployment
metadata:
  name: oldivrblast
  namespace: connecthub
  labels:
    app: oldivrblast
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: oldivrblast
  template:
    metadata:
      labels:
        app: oldivrblast
    spec:
      containers:
        - name: oldivrblast
          image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/ivrblast  # Replace with your Docker image
          ports:
            - containerPort: 80  # Change to your app's port
          env:  # Optional: Add environment variables
            - name: NODE_ENV
              value: "production"
          resources:  # Optional: Define resource limits and requests
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
