apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-callroutingdomestic
  namespace: connecthub
  labels:
    app: fastapi-callroutingdomestic
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: fastapi-callroutingdomestic
  template:
    metadata:
      labels:
        app: fastapi-callroutingdomestic
    spec:
      containers:
      - name: fastapi-callroutingdomestic
        image: 647096474516.dkr.ecr.ap-south-1.amazonaws.com/connecthubtest/callrouting-domestic   # Replace with your Docker image name
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
        - secretRef:
            name: auth-token-secrets
        - secretRef:
            name: mysql-secrets
