apiVersion: v1
kind: Service
metadata:
  name: ivrblast-service
  namespace: connecthub
spec:
  selector:
    app: ivrblast
  ports:
  - protocol: TCP
    port: 8000 # Exposed service port
    targetPort: 8000 # Port on the container
  type: ClusterIP # Change to NodePort if LoadBalancer isn't available
