apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentconversation
  - ai
  - auth
  - billing
  - callfeatures
  - callrouting
  - callroutingdomestic
  - callroutingdomesticmidregister
  - callroutingmidregister
  - chat-backend
  - clicktocall
  - confrenceconsumer
  - elevenlabs_standalone
  - emergencyivr
  - esl
  - frontend
  - gateway
  - hepipe
  - httproute
  - ingress
  - ivrblast
  - ivrblastapi
  - ivrblastauth
  - kafka
  - livemonitoring
  - longrunningtask
  - node-backend
  - predectivelogic
  - producerone
  - pvc
  - queueconsumer
  - report
  - smsdlr
  - socketioagent
  - socketioserver
  - telephony
  - whatsapp
  - whatsappdlr

namespace: connecthub