services:
  conferenceconsumer:
    build:
      context: ../..
      dockerfile: docker/livemonitoring/Dockerfile
    container_name: queueconsumer
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - connecthub_network
    volumes:
      - ../../livemonitoring/app:/app

networks:
  connecthub_network:
    driver: bridge