apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-callrouting
  namespace: connecthub
  labels:
    app: fastapi-callrouting
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: fastapi-callrouting
  template:
    metadata:
      labels:
        app: fastapi-callrouting
    spec:
      containers:
      - name: fastapi-callrouting
        image: DOCKER_IMAGE  # Replace with your Docker image name
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        envFrom:
        - secretRef:
            name: auth-token-secrets
        - secretRef:
            name: mysql-secrets
