apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
  namespace: connecthub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-storage
  resources:
    requests:
      storage: 5Gi